services:
  domain-store:
    image: postgres:16-alpine
    container_name: vecells-domain-store-local
    environment:
      POSTGRES_DB: vecells_domain
      POSTGRES_USER: vecells
      POSTGRES_PASSWORD: vecells
    ports:
      - "6543:5432"
    networks:
      - stateful_data
    volumes:
      - domain_store:/var/lib/postgresql/data

  fhir-store:
    image: postgres:16-alpine
    container_name: vecells-fhir-store-local
    environment:
      POSTGRES_DB: vecells_fhir
      POSTGRES_USER: vecells
      POSTGRES_PASSWORD: vecells
    ports:
      - "6544:5432"
    networks:
      - stateful_data
    volumes:
      - fhir_store:/var/lib/postgresql/data

volumes:
  domain_store: {}
  fhir_store: {}

networks:
  stateful_data:
    internal: true
