#!/bin/sh
set -eu

message_file="$1"
case "$message_file" in
  /*) ;;
  *) message_file="$(pwd)/$message_file" ;;
esac

repo_root="$(git rev-parse --show-toplevel)"
cd "$repo_root"

node ./tools/git-hooks/validate-commit-message.mjs "$message_file"
