import {
  FRONTEND_MANIFEST_RUNTIME_TASK_ID,
  FRONTEND_MANIFEST_RUNTIME_VISUAL_MODE,
  createFrontendContractManifestStore,
  generateFrontendContractManifest,
  type FrontendContractManifestRuntime,
  type FrontendManifestGenerationInput,
  type FrontendManifestValidationExample,
  type SeedRouteManifestSpecimen,
} from "./frontend-contract-manifest";

const SOURCE_PROMPT = "prompt/113.md";
const SOURCE_SHARED = "prompt/shared_operating_contract_106_to_115.md";
const SOURCE_RUNTIME = "blueprint/platform-runtime-and-release-blueprint.md#FrontendContractManifest";
const SOURCE_FRONTEND = "blueprint/platform-frontend-blueprint.md#Shared IA rules";
const SOURCE_KERNEL = "blueprint/canonical-ui-contract-kernel.md#Canonical contracts";
const SOURCE_A11Y =
  "blueprint/accessibility-and-content-system-contract.md#Canonical accessibility and content objects";
const SOURCE_FINDINGS = "blueprint/forensic-audit-findings.md#Finding 118";

const manifestSeeds = [
  {
    frontendContractManifestId: "FCM_113_PATIENT_PORTAL_LIVE",
    audienceSurface: "audsurf_patient_authenticated_portal",
    routeFamilyRefs: ["rf_patient_home", "rf_patient_requests"],
    gatewaySurfaceRef: "gws_patient_home",
    gatewaySurfaceRefs: ["gws_patient_home", "gws_patient_requests"],
    surfaceRouteContractRef: "ASRC_113_PATIENT_PORTAL_V1",
    surfacePublicationRef: "ASPR_113_PATIENT_PORTAL_V1",
    audienceSurfaceRuntimeBindingRef: "ASRB_113_PATIENT_PORTAL_V1",
    designContractPublicationBundleRef: "DCPB_113_PATIENT_PORTAL_V1",
    tokenKernelLayeringPolicyRef: "TKLP_SIGNAL_ATLAS_LIVE_V1",
    profileSelectionResolutionRefs: [
      "PSR_104_PATIENT_PORTAL_V1",
      "PSR_104_RF_PATIENT_HOME_V1",
      "PSR_104_RF_PATIENT_REQUESTS_V1",
    ],
    surfaceStateKernelBindingRefs: [
      "SSKB_050_RF_PATIENT_HOME_V1",
      "SSKB_050_RF_PATIENT_REQUESTS_V1",
    ],
    projectionContractVersionSetRef: "PCVS_094_PATIENT_PORTAL_V3",
    runtimePublicationBundleRef: "RPB_094_PATIENT_PORTAL_V3",
    projectionQueryContractRefs: [
      "PQC_065_RF_PATIENT_HOME_V1",
      "PQC_065_RF_PATIENT_REQUESTS_V2",
    ],
    projectionQueryContractDigestRefs: [
      "pqd::rf_patient_home::v1",
      "pqd::rf_patient_requests::v2",
    ],
    mutationCommandContractRefs: [
      "MCC_065_RF_PATIENT_HOME_ACK_V1",
      "MCC_065_RF_PATIENT_REQUESTS_CONSENT_V2",
    ],
    mutationCommandContractDigestRefs: [
      "mcd::rf_patient_home_ack::v1",
      "mcd::rf_patient_requests_consent::v2",
    ],
    liveUpdateChannelContractRefs: [
      "LUC_096_RF_PATIENT_HOME_V1",
      "LUC_096_RF_PATIENT_REQUESTS_V1",
    ],
    liveUpdateChannelDigestRefs: [
      "lcd::rf_patient_home::v1",
      "lcd::rf_patient_requests::v1",
    ],
    clientCachePolicyRef: "CCP_096_PATIENT_PORTAL_STANDARD",
    clientCachePolicyRefs: [
      "CCP_096_PATIENT_PORTAL_STANDARD",
      "CCP_096_PATIENT_PORTAL_TRANSIENT",
    ],
    clientCachePolicyDigestRefs: [
      "ccd::patient_portal_standard::v1",
      "ccd::patient_portal_transient::v1",
    ],
    commandSettlementSchemaRef: "CommandSettlementSchema::patient_portal::v3",
    commandSettlementSchemaRefs: [
      "CommandSettlementSchema::patient_portal::v3",
      "CommandSettlementSchema::patient_requests::v2",
    ],
    transitionEnvelopeSchemaRef: "TransitionEnvelopeSchema::patient_portal::v3",
    transitionEnvelopeSchemaRefs: [
      "TransitionEnvelopeSchema::patient_portal::v3",
      "TransitionEnvelopeSchema::patient_requests::v2",
    ],
    releaseRecoveryDispositionRef: "RRD_096_PATIENT_PORTAL_RESUME",
    releaseRecoveryDispositionRefs: [
      "RRD_096_PATIENT_PORTAL_RESUME",
      "RRD_096_PATIENT_PORTAL_SUMMARY_ONLY",
    ],
    routeFreezeDispositionRef: "RFD_112_PATIENT_PORTAL_NORMAL",
    routeFreezeDispositionRefs: ["RFD_112_PATIENT_PORTAL_NORMAL"],
    browserPostureState: "publishable_live",
    designContractLintVerdictRef: "DCLV_104_PATIENT_PORTAL_PASS",
    designContractLintState: "pass",
    profileLayeringDigestRef: "pld::patient_portal::v1",
    kernelPropagationDigestRef: "kpd::patient_portal::v1",
    accessibilitySemanticCoverageProfileRefs: [
      "ASCP_050_RF_PATIENT_HOME_V1",
      "ASCP_050_RF_PATIENT_REQUESTS_V1",
    ],
    automationAnchorProfileRefs: [
      "AAP_050_RF_PATIENT_HOME_V1",
      "AAP_050_RF_PATIENT_REQUESTS_V1",
    ],
    surfaceStateSemanticsProfileRefs: [
      "SSSP_050_RF_PATIENT_HOME_V1",
      "SSSP_050_RF_PATIENT_REQUESTS_V1",
    ],
    accessibilityCoverageDigestRef: "acd::patient_portal::v1",
    accessibilityCoverageState: "complete",
    projectionCompatibilityDigestRef: "pcd::patient_portal::v3",
    projectionCompatibilityState: "exact",
    runtimeBindingState: "exact",
    runtimePublicationState: "published",
    publicationParityState: "exact",
    manifestState: "current",
    generatedAt: "2026-04-13T16:00:00Z",
    source_refs: [SOURCE_PROMPT, SOURCE_SHARED, SOURCE_RUNTIME, SOURCE_FRONTEND, SOURCE_KERNEL],
  },
  {
    frontendContractManifestId: "FCM_113_PATIENT_APPOINTMENTS_READ_ONLY",
    audienceSurface: "audsurf_patient_transaction_recovery",
    routeFamilyRefs: ["rf_patient_appointments"],
    gatewaySurfaceRef: "gws_patient_appointments",
    gatewaySurfaceRefs: ["gws_patient_appointments"],
    surfaceRouteContractRef: "ASRC_113_PATIENT_APPOINTMENTS_V1",
    surfacePublicationRef: "ASPR_113_PATIENT_APPOINTMENTS_V1",
    audienceSurfaceRuntimeBindingRef: "ASRB_113_PATIENT_APPOINTMENTS_V1",
    designContractPublicationBundleRef: "DCPB_113_PATIENT_APPOINTMENTS_V1",
    tokenKernelLayeringPolicyRef: "TKLP_SIGNAL_ATLAS_LIVE_V1",
    profileSelectionResolutionRefs: ["PSR_104_RF_PATIENT_APPOINTMENTS_V1"],
    surfaceStateKernelBindingRefs: ["SSKB_050_RF_PATIENT_APPOINTMENTS_V1"],
    projectionContractVersionSetRef: "PCVS_094_PATIENT_APPOINTMENTS_V2",
    runtimePublicationBundleRef: "RPB_094_PATIENT_APPOINTMENTS_V2",
    projectionQueryContractRefs: ["PQC_065_RF_PATIENT_APPOINTMENTS_V2"],
    projectionQueryContractDigestRefs: ["pqd::rf_patient_appointments::v2"],
    mutationCommandContractRefs: ["MCC_065_RF_PATIENT_APPOINTMENTS_RESCHEDULE_V1"],
    mutationCommandContractDigestRefs: ["mcd::rf_patient_appointments_reschedule::v1"],
    liveUpdateChannelContractRefs: ["LUC_096_RF_PATIENT_APPOINTMENTS_V1"],
    liveUpdateChannelDigestRefs: ["lcd::rf_patient_appointments::v1"],
    clientCachePolicyRef: "CCP_096_PATIENT_RECOVERY_TRANSIENT",
    clientCachePolicyRefs: ["CCP_096_PATIENT_RECOVERY_TRANSIENT"],
    clientCachePolicyDigestRefs: ["ccd::patient_recovery_transient::v1"],
    commandSettlementSchemaRef: "CommandSettlementSchema::patient_appointments::v2",
    commandSettlementSchemaRefs: ["CommandSettlementSchema::patient_appointments::v2"],
    transitionEnvelopeSchemaRef: "TransitionEnvelopeSchema::patient_appointments::v2",
    transitionEnvelopeSchemaRefs: ["TransitionEnvelopeSchema::patient_appointments::v2"],
    releaseRecoveryDispositionRef: "RRD_096_PATIENT_BOOKING_SUMMARY_ONLY",
    releaseRecoveryDispositionRefs: [
      "RRD_096_PATIENT_BOOKING_SUMMARY_ONLY",
      "RRD_096_PATIENT_PORTAL_RESUME",
    ],
    routeFreezeDispositionRef: "RFD_112_PATIENT_APPOINTMENTS_READ_ONLY",
    routeFreezeDispositionRefs: ["RFD_112_PATIENT_APPOINTMENTS_READ_ONLY"],
    browserPostureState: "read_only",
    designContractLintVerdictRef: "DCLV_104_PATIENT_APPOINTMENTS_DRIFTED",
    designContractLintState: "drifted",
    profileLayeringDigestRef: "pld::patient_appointments::v1",
    kernelPropagationDigestRef: "kpd::patient_appointments::v1",
    accessibilitySemanticCoverageProfileRefs: ["ASCP_050_RF_PATIENT_APPOINTMENTS_V1"],
    automationAnchorProfileRefs: ["AAP_050_RF_PATIENT_APPOINTMENTS_V1"],
    surfaceStateSemanticsProfileRefs: ["SSSP_050_RF_PATIENT_APPOINTMENTS_V1"],
    accessibilityCoverageDigestRef: "acd::patient_appointments::v1",
    accessibilityCoverageState: "complete",
    projectionCompatibilityDigestRef: "pcd::patient_appointments::v2",
    projectionCompatibilityState: "constrained",
    runtimeBindingState: "exact",
    runtimePublicationState: "stale",
    publicationParityState: "stale",
    manifestState: "drifted",
    generatedAt: "2026-04-13T16:00:00Z",
    source_refs: [SOURCE_PROMPT, SOURCE_SHARED, SOURCE_RUNTIME, SOURCE_FRONTEND, SOURCE_FINDINGS],
  },
  {
    frontendContractManifestId: "FCM_113_SUPPORT_RECOVERY_ONLY",
    audienceSurface: "audsurf_support_workspace",
    routeFamilyRefs: ["rf_support_replay_observe"],
    gatewaySurfaceRef: "gws_support_replay_observe",
    gatewaySurfaceRefs: ["gws_support_replay_observe"],
    surfaceRouteContractRef: "ASRC_113_SUPPORT_REPLAY_V1",
    surfacePublicationRef: "ASPR_113_SUPPORT_REPLAY_V1",
    audienceSurfaceRuntimeBindingRef: "ASRB_113_SUPPORT_REPLAY_V1",
    designContractPublicationBundleRef: "DCPB_113_SUPPORT_REPLAY_V1",
    tokenKernelLayeringPolicyRef: "TKLP_SIGNAL_ATLAS_LIVE_V1",
    profileSelectionResolutionRefs: ["PSR_104_RF_SUPPORT_REPLAY_OBSERVE_V1"],
    surfaceStateKernelBindingRefs: ["SSKB_050_RF_SUPPORT_REPLAY_OBSERVE_V1"],
    projectionContractVersionSetRef: "PCVS_094_SUPPORT_REPLAY_V2",
    runtimePublicationBundleRef: "RPB_094_SUPPORT_REPLAY_V2",
    projectionQueryContractRefs: ["PQC_065_RF_SUPPORT_REPLAY_OBSERVE_V1"],
    projectionQueryContractDigestRefs: ["pqd::rf_support_replay_observe::v1"],
    mutationCommandContractRefs: ["MCC_065_RF_SUPPORT_REPLAY_RESTORE_V1"],
    mutationCommandContractDigestRefs: ["mcd::rf_support_replay_restore::v1"],
    liveUpdateChannelContractRefs: [],
    liveUpdateChannelDigestRefs: [],
    clientCachePolicyRef: "CCP_096_SUPPORT_SESSION_ONLY",
    clientCachePolicyRefs: ["CCP_096_SUPPORT_SESSION_ONLY"],
    clientCachePolicyDigestRefs: ["ccd::support_session_only::v1"],
    commandSettlementSchemaRef: "CommandSettlementSchema::support_replay::v1",
    commandSettlementSchemaRefs: ["CommandSettlementSchema::support_replay::v1"],
    transitionEnvelopeSchemaRef: "TransitionEnvelopeSchema::support_replay::v1",
    transitionEnvelopeSchemaRefs: ["TransitionEnvelopeSchema::support_replay::v1"],
    releaseRecoveryDispositionRef: "RRD_096_SUPPORT_REPLAY_RETURN_SAFE",
    releaseRecoveryDispositionRefs: ["RRD_096_SUPPORT_REPLAY_RETURN_SAFE"],
    routeFreezeDispositionRef: "RFD_112_SUPPORT_REPLAY_RECOVERY_ONLY",
    routeFreezeDispositionRefs: ["RFD_112_SUPPORT_REPLAY_RECOVERY_ONLY"],
    browserPostureState: "recovery_only",
    designContractLintVerdictRef: "DCLV_104_SUPPORT_REPLAY_PASS",
    designContractLintState: "pass",
    profileLayeringDigestRef: "pld::support_replay::v1",
    kernelPropagationDigestRef: "kpd::support_replay::v1",
    accessibilitySemanticCoverageProfileRefs: ["ASCP_050_RF_SUPPORT_REPLAY_OBSERVE_V1"],
    automationAnchorProfileRefs: ["AAP_050_RF_SUPPORT_REPLAY_OBSERVE_V1"],
    surfaceStateSemanticsProfileRefs: ["SSSP_050_RF_SUPPORT_REPLAY_OBSERVE_V1"],
    accessibilityCoverageDigestRef: "acd::support_replay::v1",
    accessibilityCoverageState: "degraded",
    projectionCompatibilityDigestRef: "pcd::support_replay::v2",
    projectionCompatibilityState: "recovery_only",
    runtimeBindingState: "stale",
    runtimePublicationState: "published",
    publicationParityState: "exact",
    manifestState: "drifted",
    generatedAt: "2026-04-13T16:00:00Z",
    source_refs: [SOURCE_PROMPT, SOURCE_SHARED, SOURCE_RUNTIME, SOURCE_FRONTEND, SOURCE_A11Y],
  },
  {
    frontendContractManifestId: "FCM_113_GOVERNANCE_BLOCKED",
    audienceSurface: "audsurf_governance_admin",
    routeFamilyRefs: ["rf_governance_shell"],
    gatewaySurfaceRef: "gws_governance_shell",
    gatewaySurfaceRefs: ["gws_governance_shell"],
    surfaceRouteContractRef: "ASRC_113_GOVERNANCE_V1",
    surfacePublicationRef: "ASPR_113_GOVERNANCE_V1",
    audienceSurfaceRuntimeBindingRef: "ASRB_113_GOVERNANCE_V1",
    designContractPublicationBundleRef: "DCPB_113_GOVERNANCE_V1",
    tokenKernelLayeringPolicyRef: "TKLP_SIGNAL_ATLAS_LIVE_V1",
    profileSelectionResolutionRefs: ["PSR_104_RF_GOVERNANCE_SHELL_V1"],
    surfaceStateKernelBindingRefs: ["SSKB_050_RF_GOVERNANCE_SHELL_V1"],
    projectionContractVersionSetRef: "PCVS_094_GOVERNANCE_V2",
    runtimePublicationBundleRef: "RPB_094_GOVERNANCE_V2",
    projectionQueryContractRefs: ["PQC_065_RF_GOVERNANCE_SHELL_V1"],
    projectionQueryContractDigestRefs: ["pqd::rf_governance_shell::v1"],
    mutationCommandContractRefs: ["MCC_065_RF_GOVERNANCE_APPROVAL_V1"],
    mutationCommandContractDigestRefs: ["mcd::rf_governance_approval::v1"],
    liveUpdateChannelContractRefs: ["LUC_096_RF_GOVERNANCE_SHELL_V1"],
    liveUpdateChannelDigestRefs: ["lcd::rf_governance_shell::v1"],
    clientCachePolicyRef: "CCP_096_GOVERNANCE_NO_REUSE",
    clientCachePolicyRefs: ["CCP_096_GOVERNANCE_NO_REUSE"],
    clientCachePolicyDigestRefs: ["ccd::governance_no_reuse::v1"],
    commandSettlementSchemaRef: "CommandSettlementSchema::governance_shell::v1",
    commandSettlementSchemaRefs: ["CommandSettlementSchema::governance_shell::v1"],
    transitionEnvelopeSchemaRef: "TransitionEnvelopeSchema::governance_shell::v1",
    transitionEnvelopeSchemaRefs: ["TransitionEnvelopeSchema::governance_shell::v1"],
    releaseRecoveryDispositionRef: "RRD_096_GOVERNANCE_BLOCKED",
    releaseRecoveryDispositionRefs: ["RRD_096_GOVERNANCE_BLOCKED"],
    routeFreezeDispositionRef: "RFD_112_GOVERNANCE_BLOCKED",
    routeFreezeDispositionRefs: ["RFD_112_GOVERNANCE_BLOCKED"],
    browserPostureState: "blocked",
    designContractLintVerdictRef: "DCLV_104_GOVERNANCE_BLOCKED",
    designContractLintState: "blocked",
    profileLayeringDigestRef: "pld::governance::v1",
    kernelPropagationDigestRef: "kpd::governance::v1",
    accessibilitySemanticCoverageProfileRefs: ["ASCP_050_RF_GOVERNANCE_SHELL_V1"],
    automationAnchorProfileRefs: ["AAP_050_RF_GOVERNANCE_SHELL_V1"],
    surfaceStateSemanticsProfileRefs: ["SSSP_050_RF_GOVERNANCE_SHELL_V1"],
    accessibilityCoverageDigestRef: "acd::governance::v1",
    accessibilityCoverageState: "blocked",
    projectionCompatibilityDigestRef: "pcd::governance::v2",
    projectionCompatibilityState: "blocked",
    runtimeBindingState: "blocked",
    runtimePublicationState: "withdrawn",
    publicationParityState: "withdrawn",
    manifestState: "rejected",
    generatedAt: "2026-04-13T16:00:00Z",
    source_refs: [SOURCE_PROMPT, SOURCE_SHARED, SOURCE_RUNTIME, SOURCE_FRONTEND, SOURCE_FINDINGS],
  },
] as const satisfies readonly FrontendManifestGenerationInput[];

export const frontendContractManifestExamples = manifestSeeds.map((seed) =>
  generateFrontendContractManifest(seed),
) as readonly FrontendContractManifestRuntime[];

const liveManifest = frontendContractManifestExamples[0]!;
const readOnlyManifest = frontendContractManifestExamples[1]!;
const recoveryManifest = frontendContractManifestExamples[2]!;
const blockedManifest = frontendContractManifestExamples[3]!;

export const frontendManifestValidationExamples = [
  {
    scenarioId: "MVC_113_PATIENT_PORTAL_LIVE",
    label: "Valid live manifest remains publishable.",
    manifest: liveManifest,
    expected: {
      validationState: "valid",
      effectiveBrowserPosture: "publishable_live",
      safeToConsume: true,
      issueCodes: [],
    },
  },
  {
    scenarioId: "MVC_113_PATIENT_APPOINTMENTS_READ_ONLY",
    label: "Design and parity drift demote the manifest to read_only.",
    manifest: readOnlyManifest,
    expected: {
      validationState: "degraded",
      effectiveBrowserPosture: "read_only",
      safeToConsume: true,
      issueCodes: [
        "design_contract_lint_drifted",
        "runtime_publication_stale",
        "publication_parity_stale",
        "projection_compatibility_constrained",
        "manifest_state_drifted",
      ],
    },
  },
  {
    scenarioId: "MVC_113_SUPPORT_RECOVERY_ONLY",
    label: "Accessibility and runtime-binding drift force recovery_only posture.",
    manifest: recoveryManifest,
    expected: {
      validationState: "degraded",
      effectiveBrowserPosture: "recovery_only",
      safeToConsume: true,
      issueCodes: [
        "accessibility_coverage_degraded",
        "runtime_binding_stale",
        "projection_compatibility_constrained",
        "manifest_state_drifted",
      ],
    },
  },
  {
    scenarioId: "MVC_113_GOVERNANCE_BLOCKED",
    label: "Withdrawn runtime publication fails closed.",
    manifest: blockedManifest,
    expected: {
      validationState: "rejected",
      effectiveBrowserPosture: "blocked",
      safeToConsume: false,
      issueCodes: [
        "design_contract_lint_blocked",
        "accessibility_coverage_blocked",
        "runtime_binding_blocked",
        "runtime_publication_withdrawn",
        "publication_parity_withdrawn",
        "projection_compatibility_blocked",
        "manifest_state_rejected",
      ],
    },
  },
  {
    scenarioId: "MVC_113_DIGEST_MISMATCH",
    label: "Digest mismatch rejects the manifest immediately.",
    manifest: {
      ...liveManifest,
      frontendContractDigestRef: "frontend-contract-digest::tampered",
    },
    expected: {
      validationState: "rejected",
      effectiveBrowserPosture: "blocked",
      safeToConsume: false,
      issueCodes: ["frontend_contract_digest_drift"],
    },
  },
  {
    scenarioId: "MVC_113_MISSING_RUNTIME_BINDING",
    label: "Missing runtime binding ref is rejected.",
    manifest: generateFrontendContractManifest({
      ...liveManifest,
      audienceSurfaceRuntimeBindingRef: "",
      frontendContractDigestRef: undefined,
      designContractDigestRef: undefined,
      surfaceAuthorityTupleHash: undefined,
      driftState: undefined,
      frontendContractDigestVerdict: undefined,
      designContractDigestVerdict: undefined,
      surfaceAuthorityTupleVerdict: undefined,
    }),
    expected: {
      validationState: "rejected",
      effectiveBrowserPosture: "blocked",
      safeToConsume: false,
      issueCodes: ["missing_audienceSurfaceRuntimeBindingRef"],
    },
  },
] as const satisfies readonly FrontendManifestValidationExample[];

export const seedRouteManifestSpecimens = [
  {
    specimenId: "SRS_113_PATIENT_HOME",
    manifestRef: liveManifest.frontendContractManifestId,
    routeFamilyRef: "rf_patient_home",
    shellLabel: "Patient portal shell",
    selectedAnchor: "Continue the next safe step",
    requiredDomMarkers: [
      "data-browser-posture",
      "data-manifest-drift-state",
      "data-seed-route-validity",
      "data-selected-anchor",
    ],
    source_refs: [SOURCE_PROMPT, SOURCE_FRONTEND],
  },
  {
    specimenId: "SRS_113_PATIENT_APPOINTMENTS",
    manifestRef: readOnlyManifest.frontendContractManifestId,
    routeFamilyRef: "rf_patient_appointments",
    shellLabel: "Patient recovery shell",
    selectedAnchor: "Review the last safe appointment summary",
    requiredDomMarkers: [
      "data-browser-posture",
      "data-manifest-drift-state",
      "data-seed-route-validity",
      "data-selected-anchor",
    ],
    source_refs: [SOURCE_PROMPT, SOURCE_FRONTEND],
  },
  {
    specimenId: "SRS_113_SUPPORT_REPLAY",
    manifestRef: recoveryManifest.frontendContractManifestId,
    routeFamilyRef: "rf_support_replay_observe",
    shellLabel: "Support replay shell",
    selectedAnchor: "Resume the bounded replay step",
    requiredDomMarkers: [
      "data-browser-posture",
      "data-manifest-drift-state",
      "data-seed-route-validity",
      "data-selected-anchor",
    ],
    source_refs: [SOURCE_PROMPT, SOURCE_FRONTEND],
  },
  {
    specimenId: "SRS_113_GOVERNANCE",
    manifestRef: blockedManifest.frontendContractManifestId,
    routeFamilyRef: "rf_governance_shell",
    shellLabel: "Governance control shell",
    selectedAnchor: "Return to the last approved review packet",
    requiredDomMarkers: [
      "data-browser-posture",
      "data-manifest-drift-state",
      "data-seed-route-validity",
      "data-selected-anchor",
    ],
    source_refs: [SOURCE_PROMPT, SOURCE_FRONTEND],
  },
] as const satisfies readonly SeedRouteManifestSpecimen[];

export const frontendManifestRuntimeCatalog = {
  taskId: FRONTEND_MANIFEST_RUNTIME_TASK_ID,
  visualMode: FRONTEND_MANIFEST_RUNTIME_VISUAL_MODE,
  manifestExampleCount: frontendContractManifestExamples.length,
  validationScenarioCount: frontendManifestValidationExamples.length,
  seedRouteSpecimenCount: seedRouteManifestSpecimens.length,
  failClosedPostures: ["read_only", "recovery_only", "blocked"],
  schemaArtifactPaths: [
    "packages/api-contracts/schemas/frontend-contract-manifest.schema.json",
    "packages/api-contracts/schemas/frontend-contract-manifest-runtime.schema.json",
    "packages/api-contracts/schemas/frontend-contract-manifest-verdict.schema.json",
  ],
  digestJoinCount: 6,
} as const;

export const frontendManifestRuntimeSchemas = [
  {
    schemaId: "FrontendContractManifest",
    artifactPath: "packages/api-contracts/schemas/frontend-contract-manifest.schema.json",
    generatedByTask: "seq_050",
  },
  {
    schemaId: "FrontendContractManifestRuntime",
    artifactPath: "packages/api-contracts/schemas/frontend-contract-manifest-runtime.schema.json",
    generatedByTask: FRONTEND_MANIFEST_RUNTIME_TASK_ID,
  },
  {
    schemaId: "FrontendContractManifestVerdict",
    artifactPath: "packages/api-contracts/schemas/frontend-contract-manifest-verdict.schema.json",
    generatedByTask: FRONTEND_MANIFEST_RUNTIME_TASK_ID,
  },
] as const;

export const frontendManifestStore = createFrontendContractManifestStore(
  frontendContractManifestExamples,
);
