export {
  ASSISTIVE_RAIL_VISUAL_MODE,
  AssistiveCapabilityPostureChip,
  AssistiveObserveOnlyPlaceholder,
  AssistiveProvenanceFooterStub,
  AssistiveRailCollapseToggle,
  AssistiveRailHeader,
  AssistiveRailKeyboardController,
  AssistiveRailShell,
  AssistiveRailStateAdapter,
  AssistiveShadowModePanel,
  AssistiveSummaryStubCard,
} from "./assistive-rail";
export type {
  AssistiveRailActionabilityState,
  AssistiveRailPresentationState,
  AssistiveRailShellState,
  AssistiveRailStateAdapterInput,
  AssistiveRailTrustState,
} from "./assistive-rail";
export {
  ASSISTIVE_DRAFT_VISUAL_MODE,
  AssistiveBeforeAfterToggle,
  AssistiveBoundedInsertBar,
  AssistiveDraftDiffBlock,
  AssistiveDraftKeyboardNavigator,
  AssistiveDraftSectionCard,
  AssistiveDraftSectionDeck,
  AssistiveInsertBlockReason,
  AssistivePatchLeaseStatus,
  AssistiveSectionActionCluster,
  AssistiveTargetSlotPill,
  buildAssistiveDraftDeckState,
} from "./assistive-draft";
export type {
  AssistiveDraftBlockReason,
  AssistiveDraftCompareMode,
  AssistiveDraftDeckState,
  AssistiveDraftDiffLine,
  AssistiveDraftLeaseState,
  AssistiveDraftPatchLease,
  AssistiveDraftSection,
  AssistiveDraftSessionState,
  AssistiveDraftSlotState,
  AssistiveDraftStateAdapterInput,
  AssistiveDraftTargetSlot,
} from "./assistive-draft";
export {
  ASSISTIVE_CONFIDENCE_VISUAL_MODE,
  AssistiveConfidenceBand,
  AssistiveConfidenceBandCluster,
  AssistiveConfidenceStateAdapter,
  AssistiveConfidenceSuppressionState,
  AssistiveEvidenceCoverageMiniMap,
  AssistiveFactorRowList,
  AssistiveFreshnessLine,
  AssistiveProvenanceDrawer,
  AssistiveProvenanceFooter,
  AssistiveRationaleDigest,
  AssistiveRationaleExplainer,
} from "./assistive-confidence";
export type {
  AssistiveConfidenceBandTone,
  AssistiveConfidenceDisplayBand,
  AssistiveConfidenceFactor,
  AssistiveConfidenceFactorKind,
  AssistiveConfidencePresentationDepth,
  AssistiveConfidenceState,
  AssistiveConfidenceStateAdapterInput,
  AssistiveConfidenceSuppressionReason,
  AssistiveEvidenceCoverageSegment,
  AssistiveEvidenceCoverageState,
  AssistiveFreshnessState,
  AssistiveProvenanceEnvelopeSummary,
} from "./assistive-confidence";
export {
  ASSISTIVE_OVERRIDE_VISUAL_MODE,
  AssistiveApprovalBurdenNotice,
  AssistiveEditDeltaDrawer,
  AssistiveEditDeltaSummary,
  AssistiveEditedByClinicianTrail,
  AssistiveHumanArtifactSummary,
  AssistiveOverrideReasonCodeGroup,
  AssistiveOverrideReasonSheet,
  AssistiveOverrideReasonValidationState,
  AssistiveOverrideStateAdapter,
  AssistiveOverrideTrailEventRow,
} from "./assistive-override";
export type {
  AssistiveFinalHumanArtifactSummary,
  AssistiveOverrideDiffKind,
  AssistiveOverrideDiffLine,
  AssistiveOverrideDisposition,
  AssistiveOverrideReasonCode,
  AssistiveOverrideReasonCodeDefinition,
  AssistiveOverrideReasonRequirement,
  AssistiveOverrideScope,
  AssistiveOverrideState,
  AssistiveOverrideStateAdapterInput,
  AssistiveOverrideTrailEvent,
} from "./assistive-override";
export {
  ASSISTIVE_TRUST_POSTURE_VISUAL_MODE,
  AssistiveBlockedByPolicyPanel,
  AssistiveDegradedStatePanel,
  AssistiveFrozenStatePanel,
  AssistiveObserveOnlyNotice,
  AssistiveQuarantinedStatePanel,
  AssistiveRecoveryActionPanel,
  AssistiveShadowOnlyNotice,
  AssistiveTrustStateAdapter,
  AssistiveTrustStateChip,
  AssistiveTrustStateFrame,
} from "./assistive-trust-posture";
export type {
  AssistiveActionabilityState,
  AssistiveConfidencePostureState,
  AssistiveDominantAction,
  AssistiveSurfacePostureState,
  AssistiveTrustPostureKind,
  AssistiveTrustPostureState,
  AssistiveTrustReason,
  AssistiveTrustState,
  AssistiveTrustStateAdapterInput,
} from "./assistive-trust-posture";
export {
  ASSISTIVE_FREEZE_RECOVERY_VISUAL_MODE,
  AssistiveFreezeInPlaceFrame,
  AssistiveFreezeReasonList,
  AssistiveFreezeRecoveryStateAdapter,
  AssistivePreservedArtifactView,
  AssistiveRecoverableNotice,
  AssistiveRecoveryExplanationPanel,
  AssistiveRecoveryFocusManager,
  AssistiveRegenerateInPlaceActionBar,
  AssistiveStaleControlSuppression,
  AssistiveStaleSessionBanner,
} from "./assistive-stale-recovery";
export type {
  AssistiveFreezeDominantAction,
  AssistiveFreezeDriftCategory,
  AssistiveFreezeReason,
  AssistiveFreezeRecoveryActionability,
  AssistiveFreezeRecoveryDisposition,
  AssistiveFreezeRecoveryState,
  AssistiveFreezeRecoveryStateAdapterInput,
  AssistiveFreezeRecoveryStatus,
  AssistivePreservedArtifact,
} from "./assistive-stale-recovery";
export {
  ASSISTIVE_SAME_SHELL_STAGE_VISUAL_MODE,
  AssistiveAnchorSyncBridge,
  AssistiveAttentionBudgetCoordinator,
  AssistiveDecisionDockCoexistenceFrame,
  AssistiveResponsiveFoldController,
  AssistiveStagePinController,
  AssistiveStagePromoter,
  AssistiveSummaryStubCluster,
  AssistiveWorkspaceStageBindingView,
  AssistiveWorkspaceStageHost,
  AssistiveWorkspaceStageStateAdapter,
} from "./assistive-workspace-stage";
export type {
  AssistiveStagePromotionState,
  AssistiveWorkspaceStageActionability,
  AssistiveWorkspaceStageFixture,
  AssistiveWorkspaceStageMode,
  AssistiveWorkspaceStageState,
  AssistiveWorkspaceStageStateAdapterInput,
  AssistiveWorkspaceStageTrustState,
} from "./assistive-workspace-stage";
export {
  ASSISTIVE_QUEUE_ASSURANCE_VISUAL_MODE,
  AssistiveCrossSurfaceRecoveryFrame,
  AssistiveOpsIncidentAndFreezeStrip,
  AssistiveOpsTrustSummaryCard,
  AssistiveQueueAndAssuranceMergeAdapter,
  AssistiveQueueContextPocket,
  AssistiveQueueCue,
  AssistiveQueueOpenToStageBridge,
  AssistiveQueueTrustBadge,
  AssistiveReleaseAssuranceSummaryCard,
  AssistiveReleaseCandidateDeltaBadge,
  buildAssistiveQueueAndAssuranceMergeState,
} from "./assistive-queue-assurance-merge";
export type {
  AssistiveContinuumActionability,
  AssistiveContinuumPosture,
  AssistiveQueueAndAssuranceMergeAdapterInput,
  AssistiveQueueAndAssuranceMergeState,
} from "./assistive-queue-assurance-merge";
export {
  ActiveTaskShell,
  CasePulseBand,
  ConsequenceStack,
  DecisionDock,
  DeltaStack,
  EvidenceStack,
  PromotedSupportRegion,
  ReferenceStack,
  SummaryStack,
  TaskCanvas,
  TaskStatusStrip,
} from "./workspace-active-task-shell";
export {
  StaffShellSeedApp,
  WorkspaceHeaderBand,
  WorkspaceHome,
  WorkspaceNavRail,
  WorkspaceRouteFamilyController,
  WorkspaceShell,
  WorkspaceStatusStrip,
} from "./staff-shell-seed";
export {
  QueueAnchorStub,
  QueueChangeBatchBanner,
  QueuePreviewPocket,
  QueueRow,
  QueueScanManager,
  QueueToolbar,
  QueueWorkboardFrame,
} from "./workspace-queue-workboard";
export {
  BufferedQueueChangeTray,
  CompletionContinuityStage,
  DepartureReturnStub,
  NextTaskPostureCard,
  ProtectedCompositionRecovery,
  WorkspaceProtectionStrip,
} from "./workspace-focus-continuity";
export {
  CallbackAttemptTimeline,
  CallbackDetailSurface,
  CallbackExpectationCard,
  CallbackOutcomeCapture,
  CallbackRouteRepairPrompt,
  CallbackWorklistRoute,
} from "./workspace-callback-workbench";

export function isWorkspaceShellPath(pathname: string): boolean {
  return pathname === "/workspace" || pathname.startsWith("/workspace/");
}
