BEGIN;

CREATE TABLE IF NOT EXISTS phase1_triage_tasks (
  triage_task_id TEXT PRIMARY KEY,
  request_ref TEXT NOT NULL UNIQUE,
  request_lineage_ref TEXT NOT NULL,
  submission_promotion_record_ref TEXT NOT NULL,
  normalized_submission_ref TEXT NOT NULL,
  receipt_consistency_key TEXT NOT NULL,
  status_consistency_key TEXT NOT NULL,
  request_type_ref TEXT NOT NULL,
  service_band_ref TEXT NOT NULL,
  residual_review_state TEXT NOT NULL,
  workflow_queue_ref TEXT NOT NULL,
  task_state TEXT NOT NULL,
  safety_state TEXT NOT NULL,
  residual_risk_rule_refs_json TEXT NOT NULL,
  priority_band_ref TEXT NOT NULL,
  queue_rank INTEGER NOT NULL,
  latest_eta_forecast_ref TEXT NOT NULL,
  latest_status_projection_ref TEXT NOT NULL,
  schema_resolution_ref TEXT NOT NULL,
  created_at TEXT NOT NULL,
  updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS phase1_triage_eta_forecasts (
  triage_eta_forecast_id TEXT PRIMARY KEY,
  triage_task_ref TEXT NOT NULL,
  request_ref TEXT NOT NULL,
  request_lineage_ref TEXT NOT NULL,
  receipt_consistency_key TEXT NOT NULL,
  queue_snapshot_id TEXT NOT NULL,
  snapshot_observed_at TEXT NOT NULL,
  telemetry_freshness_state TEXT NOT NULL,
  queue_completeness_state TEXT NOT NULL,
  staffing_coverage_state TEXT NOT NULL,
  queue_rank INTEGER NOT NULL,
  queue_size INTEGER NOT NULL,
  policy_version_ref TEXT NOT NULL,
  calibration_version_ref TEXT NOT NULL,
  eta_promise_ref TEXT NOT NULL,
  hysteresis_policy_ref TEXT NOT NULL,
  working_schedule_ref TEXT NOT NULL,
  simulation_seed TEXT NOT NULL,
  draw_count INTEGER NOT NULL,
  candidate_receipt_bucket TEXT NOT NULL,
  candidate_bucket_confidence REAL NOT NULL,
  receipt_bucket TEXT NOT NULL,
  promise_state TEXT NOT NULL,
  eta_lower_bound_at TEXT,
  eta_median_at TEXT,
  eta_upper_bound_at TEXT,
  calibrated_lower_working_minutes REAL NOT NULL,
  calibrated_median_working_minutes REAL NOT NULL,
  calibrated_upper_working_minutes REAL NOT NULL,
  bucket_confidence REAL NOT NULL,
  raw_bucket_probabilities_json TEXT NOT NULL,
  calibrated_bucket_probabilities_json TEXT NOT NULL,
  admissible_buckets_json TEXT NOT NULL,
  conformal_padding_working_minutes REAL NOT NULL,
  hysteresis_decision TEXT NOT NULL,
  generated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS phase1_patient_status_projections (
  patient_status_projection_id TEXT PRIMARY KEY,
  request_ref TEXT NOT NULL,
  request_lineage_ref TEXT NOT NULL,
  triage_task_ref TEXT,
  receipt_consistency_key TEXT NOT NULL,
  status_consistency_key TEXT NOT NULL,
  macro_state TEXT NOT NULL,
  summary_state TEXT NOT NULL,
  next_step_message_ref TEXT NOT NULL,
  trust_cue_ref TEXT NOT NULL,
  visible_eta_bucket TEXT NOT NULL,
  promise_state TEXT NOT NULL,
  safety_state TEXT NOT NULL,
  residual_risk_rule_refs_json TEXT NOT NULL,
  mapping_contract_ref TEXT NOT NULL,
  last_meaningful_update_at TEXT NOT NULL,
  generated_at TEXT NOT NULL
);

COMMIT;
