-- 148_phase5_alternative_offer_engine.sql
-- Phase 5 alternative-offer optimisation, secure patient choice, and regeneration persistence.
-- Depends on:
--   143_phase5_hub_case_kernel.sql
--   146_phase5_network_capacity_snapshot_pipeline.sql
--   147_phase5_hub_queue_engine.sql
-- Uses canonical access grants from the identity-access backbone public surface.

create table if not exists phase5_alternative_offer_optimisation_plans (
  alternative_offer_optimisation_plan_id text primary key,
  hub_coordination_case_id text not null,
  candidate_snapshot_ref text not null,
  decision_plan_ref text not null,
  capacity_rank_proof_ref text not null,
  rank_plan_version_ref text not null,
  policy_tuple_hash text not null,
  offer_set_hash text not null,
  represented_bucket_keys jsonb not null default '[]'::jsonb,
  visible_candidate_refs jsonb not null default '[]'::jsonb,
  excluded_candidates jsonb not null default '[]'::jsonb,
  callback_fallback_eligible boolean not null default false,
  objective_score numeric not null default 0,
  generated_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);

create table if not exists phase5_alternative_offer_sessions (
  alternative_offer_session_id text primary key,
  hub_coordination_case_id text not null,
  optimisation_plan_ref text not null,
  candidate_snapshot_ref text not null,
  capacity_rank_proof_ref text not null,
  access_grant_ref text not null,
  truth_projection_ref text not null,
  visible_offer_set_hash text not null,
  offer_mode text not null,
  patient_choice_state text not null,
  open_choice_state text not null,
  callback_offer_state text not null,
  subject_ref text not null,
  session_epoch_ref text not null,
  subject_binding_version_ref text not null,
  manifest_version_ref text,
  release_approval_freeze_ref text not null,
  channel_release_freeze_state text not null,
  surface_route_contract_ref text not null,
  surface_publication_ref text not null,
  runtime_publication_bundle_ref text not null,
  selected_anchor_ref text not null,
  selected_anchor_tuple_hash_ref text not null,
  experience_continuity_evidence_ref text not null,
  latest_regeneration_settlement_ref text,
  selected_candidate_ref text,
  superseded_by_offer_session_ref text,
  superseded_at timestamptz,
  expires_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);

create table if not exists phase5_alternative_offer_entries (
  alternative_offer_entry_id text primary key,
  alternative_offer_session_id text not null,
  hub_coordination_case_id text not null,
  candidate_ref text not null,
  slot_candidate_ref text not null,
  capacity_unit_ref text not null,
  site_id text not null,
  local_day_bucket text not null,
  modality text not null,
  capacity_rank_explanation_ref text not null,
  rank_ordinal integer not null,
  bucket_key text not null,
  coverage_role text not null,
  redundancy_penalty_class text not null,
  recommendation_state text not null,
  selection_state text not null,
  availability_window_start_at timestamptz not null,
  availability_window_end_at timestamptz not null,
  patient_facing_label text not null,
  patient_reason_cue_refs jsonb not null default '[]'::jsonb,
  staff_reason_cue_refs jsonb not null default '[]'::jsonb,
  route_family_ref text not null,
  truth_tuple_hash text not null,
  policy_tuple_hash text not null,
  generated_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);

create table if not exists phase5_alternative_offer_fallback_cards (
  alternative_offer_fallback_card_id text primary key,
  offer_session_ref text not null,
  hub_coordination_case_id text not null,
  card_type text not null,
  source_fallback_ref text,
  display_placement text not null,
  eligibility_state text not null,
  reason_code_refs jsonb not null default '[]'::jsonb,
  lead_time_constraint_ref text,
  dominant_action_ref text not null,
  generated_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);

create table if not exists phase5_alternative_offer_regeneration_settlements (
  alternative_offer_regeneration_settlement_id text primary key,
  hub_coordination_case_id text not null,
  previous_offer_session_ref text not null,
  next_offer_session_ref text,
  previous_offer_set_hash text not null,
  next_offer_set_hash text,
  trigger_class text not null,
  preserved_selected_anchor_ref text not null,
  preserved_selected_anchor_tuple_hash_ref text not null,
  preserved_offer_entry_refs jsonb not null default '[]'::jsonb,
  preserved_fallback_card_ref text,
  result_state text not null,
  recorded_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);

create table if not exists phase5_alternative_offer_selection_events (
  alternative_offer_selection_event_id text primary key,
  hub_coordination_case_id text not null,
  offer_session_ref text not null,
  offer_entry_ref text,
  fallback_card_ref text,
  event_type text not null,
  actor_ref text not null,
  actor_kind text not null,
  decision_reason_refs jsonb not null default '[]'::jsonb,
  truth_tuple_hash text not null,
  recorded_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);

create table if not exists phase5_offer_secure_link_bindings (
  offer_secure_link_binding_id text primary key,
  hub_coordination_case_id text not null,
  offer_session_ref text not null,
  access_grant_ref text not null,
  governing_object_ref text not null,
  governing_version_ref text not null,
  route_family_ref text not null,
  route_intent_ref text not null,
  token_key_version_ref text not null,
  validator_version_ref text not null,
  transport_class text not null,
  subject_ref text not null,
  bound_patient_ref text not null,
  session_epoch_ref text not null,
  subject_binding_version_ref text not null,
  manifest_version_ref text,
  release_approval_freeze_ref text not null,
  channel_release_freeze_state text not null,
  visibility_envelope_version_ref text not null,
  visible_offer_set_hash text not null,
  truth_tuple_hash text not null,
  offer_fence_epoch integer not null,
  recovery_route_ref text not null,
  created_at timestamptz not null,
  expires_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);

create table if not exists phase5_hub_offer_truth_projections (
  hub_offer_to_confirmation_truth_projection_id text primary key,
  hub_coordination_case_id text not null,
  selection_source text not null,
  candidate_snapshot_ref text,
  selected_candidate_ref text,
  selected_candidate_source_version text,
  selected_capacity_unit_ref text,
  offer_session_ref text,
  offer_optimisation_plan_ref text,
  fallback_card_ref text,
  offer_set_hash text,
  offer_session_revision integer not null default 0,
  offer_expiry_at timestamptz,
  offer_state text not null,
  offer_actionability_state text not null,
  latest_regeneration_settlement_ref text,
  commit_attempt_ref text,
  booking_evidence_ref text,
  confirmation_gate_ref text,
  hub_appointment_id text,
  practice_acknowledgement_ref text,
  practice_ack_generation integer not null default 0,
  fallback_ref text,
  fallback_link_state text not null,
  confirmation_truth_state text not null,
  patient_visibility_state text not null,
  practice_visibility_state text not null,
  closure_state text not null,
  experience_continuity_evidence_ref text,
  policy_tuple_hash text not null,
  truth_tuple_hash text not null,
  blocking_refs jsonb not null default '[]'::jsonb,
  causal_token text not null,
  monotone_revision integer not null default 1,
  generated_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);

create table if not exists phase5_alternative_offer_read_back_captures (
  alternative_offer_read_back_capture_id text primary key,
  hub_coordination_case_id text not null,
  offer_session_ref text not null,
  selected_offer_entry_ref text,
  selected_fallback_card_ref text,
  spoken_summary text not null,
  confirmed_subject_ref text not null,
  caller_relationship text not null,
  confirmation_phrase text not null,
  decision text not null,
  captured_by text not null,
  recorded_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);

create table if not exists phase5_alternative_offer_replay_fixtures (
  alternative_offer_replay_fixture_id text primary key,
  hub_coordination_case_id text not null,
  offer_session_ref text not null,
  optimisation_plan_ref text not null,
  candidate_snapshot_ref text not null,
  decision_plan_ref text not null,
  capacity_rank_proof_ref text not null,
  visible_candidate_refs jsonb not null default '[]'::jsonb,
  represented_bucket_keys jsonb not null default '[]'::jsonb,
  offer_set_hash text not null,
  policy_tuple_hash text not null,
  recorded_at timestamptz not null,
  source_refs jsonb not null default '[]'::jsonb,
  version integer not null
);
